### ISSUE TITLE
Enable CodeClimate and test coverage reporting

### ISSUE THREAD

**Issue by cruisercohen** [vacasaoss/serverless-secret-baker#14]
**Is your feature request related to a problem? Please describe.**
Need Code Climate and test coverage reporting for proper build

**Describe the solution you'd like**
Enable Code Climate
re-enable test coverage reporting once code climate is hooked up
need DevOps org level support

I think all we need to do is revert #15  and add `CC_TEST_REPORTER_ID` to CircleCI Environment Variables

**Describe alternatives you've considered**
none

**Additional context**
this is part of moving to the new OSS organization.

**Comment by mccredie** [comment]
Complete
