### ISSUE TITLE
List Plugin on appropriate listings

### ISSUE THREAD

**Issue by cruisercohen** [vacasaoss/serverless-secret-baker#21]
**Is your feature request related to a problem? Please describe.**
Nobody knows about our plugin yet

**Describe the solution you'd like**

- Find and add ourselves to any relevant package listings
- Example https://github.com/serverless/plugins
- Forums could be another place to list ourselves?

**Describe alternatives you've considered**
Not letting people know about our plugin

**Additional context**

**Comment by mccredie** [comment]
It looks like our pull request on serverless/plugins has been merged.  We should mark this as done.  If there are other listings we want to add to, we can do that separately.

**Comment by cruisercohen** [comment]
If you want to close can you create a new issue to look for other ones? Or we can finish looking at a future meeting

**Comment by mccredie** [comment]
Let's discuss this in the meeting this week (9/19/19). I think it is done, but if there are other things we want to do to advertise this package we can create new issues for them.

**Comment by mccredie** [comment]
I have it to discuss creating a presentation for meetups / etc in a future meeting.
