### ISSUE TITLE
Automatically trigger publish pipeline when a tag is created

### ISSUE THREAD

**Issue by mccredie** [vacasaoss/serverless-secret-baker#26]
**Is your feature request related to a problem? Please describe.**
Currently we are publishing to npm from a laptop.  We should automate this.

**Describe the solution you'd like**
Setup a circleci pipeline that
1. Is triggered by a tag
2. Verifies that the tag matches the version in the package.json file
3. runs 'npm package --dry-run'
4. Waits for an approval
5. Publishes to npm upon approval

Note, we may also optionally run unit tests etc. But I'm assuming those will be run with each merge request, so it shouldn't be necessary.

**Describe alternatives you've considered**

* Keep doing it the way we have been
* omit the approve step

**Additional context**

**Comment by mccredie** [comment]
I think this can be closed. There is an open PR, but the functionality already works.

**Comment by cruisercohen** [comment]
👍
