### ISSUE TITLE
Add Branding and Logos

### ISSUE THREAD

**Issue by cruisercohen** [vacasaoss/serverless-secret-baker#3]
We got logos! They are awesome! Add them to the project
(I got these from the slack channel, is there an original version we should use @mccredie ?

![](https://user-images.githubusercontent.com/1832296/58922781-53a3e100-86f1-11e9-8a92-c34f22241cc8.png)

**Comment by mccredie** [comment]
[SecretChefIcons.zip](https://github.com/vacasaoss/serverless-secret-baker/files/3507428/SecretChefIcons.zip)

**Comment by mccredie** [comment]
![1055_SecretChefGraphicsV1_5@100x](https://user-images.githubusercontent.com/4380779/63980279-f0b3b300-ca6f-11e9-9953-1afba2a45b18.png)
![1055_SecretChefGraphicsV1_1@100x](https://user-images.githubusercontent.com/4380779/63980299-fd380b80-ca6f-11e9-8018-0de94ec53c16.png)
![1055_SecretChefGraphicsV1_2@100x](https://user-images.githubusercontent.com/4380779/63980300-fd380b80-ca6f-11e9-9297-96dbe0334c05.png)
![1055_SecretChefGraphicsV1_3@100x](https://user-images.githubusercontent.com/4380779/63980301-fdd0a200-ca6f-11e9-8bd2-1dc0c12ed771.png)
![1055_SecretChefGraphicsV1_4@100x](https://user-images.githubusercontent.com/4380779/63980303-fdd0a200-ca6f-11e9-99e8-8c2012b1c90f.png)
![1055_SecretChefGraphicsV1_6@100x](https://user-images.githubusercontent.com/4380779/63980305-fdd0a200-ca6f-11e9-8465-a334b7f0e8f0.png)
