### ISSUE TITLE
Add a release template

### ISSUE THREAD

**Issue by cruisercohen** [vacasaoss/serverless-secret-baker#5]
Is your feature request related to a problem? Please describe.
We should have consistent release format

Describe the solution you'd like
make a template

Describe alternatives you've considered
inconsistant looking releases?

Additional context

**Comment by mccredie** [comment]
I see this: https://stackoverflow.com/questions/56798253/release-template-for-github 

So github doesn't support release templates.  But there is a project: https://github.com/apps/release-drafter

It looks kinda cool. It works as a plugin though, don't know if we want to give it permissions to our project.  Worth discussing anyway.

**Comment by mccredie** [comment]
After some discussion, we decided that this doesn't really provide value at this time.
